---

docker_image: &docker_image
  docker:
    - image: circleci/buildpack-deps:stable-curl

docker_login: &docker_login
  name: "Docker Login"
  command: |
    docker login -u $DOCKER_USER -p $DOCKER_PASS

build_latest: &build_latest
  name: "Docker Build Latest"
  command: |
    docker build --build-arg TF_VERSION=$TF_VERSION --tag $IMAGE_NAME:latest .

#    docker push $IMAGE_NAME:latest

build_local: &build_local
  name: "Docker Build Local Image"
  command: |
    echo "Building version $TF_VERSION with Docker Tag of $TAG"
    docker build --tag hermes .

build_image: &build_image
  name: "Docker Build Image"
  command: |
    echo "Building version $TF_VERSION with Docker Tag of $TAG"
    docker build --build-arg TF_VERSION=$TF_VERSION --tag $IMAGE_NAME:$TAG .

#    docker push $IMAGE_NAME:$TAG
  requires:
      - "Docker Build Latest"

build_branches: &build_branches
  name: "Docker Build Feature Branch"
  command: |
    docker build -t $IMAGE_NAME:$CIRCLE_USERNAME-$TAG-$CIRCLE_SHA1 .

#    docker push $IMAGE_NAME:$CIRCLE_USERNAME-$TAG-$CIRCLE_SHA1

project_env_vars: &project_env_vars
  environment:
    IMAGE_NAME: asicsdigital/hermes

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          context: org-global
          filters:
            branches:
              only: master

      - build_0.X:
          context: org-global
          filters:
            branches:
              ignore: master

version: 2
jobs:
  build_and_deploy:
    <<: *docker_image
    <<: *project_env_vars
    steps:
      - checkout
      - setup_remote_docker
      - run:
          <<: *docker_login
      - run:
          environment:
            TF_VERSION: 0.11.8
          <<: *build_latest
      - run:
          environment:
            TF_VERSION: 0.11.8
            TAG: 0.11.8
          <<: *build_image
      - run:
          environment:
            TF_VERSION: 0.11.7
            TAG: 0.11.7
          <<: *build_image
      - run:
          environment:
            TF_VERSION: 0.11.6
            TAG: 0.11.6
          <<: *build_image
      - run:
          environment:
            TF_VERSION: 0.11.5
            TAG: 0.11.5
          <<: *build_image
      - run:
          environment:
            TF_VERSION: 0.11.4
            TAG: 0.11.4
          <<: *build_image
      - run:
          environment:
            TF_VERSION: 0.11.3
            TAG: 0.11.3
          <<: *build_image
      - run:
          environment:
            TF_VERSION: 0.11.2
            TAG: 0.11.2
          <<: *build_image
      - run:
          environment:
            TF_VERSION: 0.11.1
            TAG: 0.11.1
          <<: *build_image
      - run:
          environment:
            TF_VERSION: 0.10.8
            TAG: 0.10.8
          <<: *build_image

  build_0.X:
    <<: *docker_image
    <<: *project_env_vars
    steps:
      - checkout
      - setup_remote_docker
      - run:
          <<: *docker_login
      - run:
          working_directory: ~/project/0.X
          environment:
          <<: *build_local
      - run:
          working_directory: ~/project/0.X
          environment:
            TAG: core
          <<: *build_branches
      - run:
          working_directory: ~/project/0.X/terraform
          environment:
            TAG: terraform
          <<: *build_branches
