#!/usr/bin/env bash
# shellcheck shell=bash

#PW=$(curl -s \
#  -H "X-Vault-Token: $(cat ~/.vault-token )" \
#  -X GET ${VAULT_ADDR}/v1/secret/consul_htpasswd \
#  | jq -r .data.value ) ; \
#  echo "consul_htpasswd = \"$PW\"" \
#  > _consul_htpasswd.auto.tfvars


if [ -e /bin/vault ]; then
  if [[ "$VAULT_ADDR" ]]; then
    CONSUL_PASSWORD=$(vault read -field value secret/consul_htpasswd)
    echo "consul_htpasswd = \"$CONSUL_PASSWORD\"" > _consul_htpasswd.auto.tfvars 
  else
    echo "MISSING VAULT_ADDR"
  fi
fi
