#!/usr/bin/env bash
# shellcheck shell=bash

approle_authenticate () {
  curl -s \
    -X POST \
    -d ${VAULT_PAYLOAD} \
    ${VAULT_ADDR}/v1/auth/approle/login \
    | jq -r .auth.client_token \
    > $HOME/.vault-token
}

if [ -e /bin/vault ]; then
  #if [[ "$VAULT_ADDR" && "$VAULT_AUTH_GITHUB_TOKEN" ]]; then
  if [[ "$VAULT_ADDR" ]]; then
    # are we already authenticated?
    TOKEN_LOOKUP=$(vault token-lookup -format=json 2>/dev/null)

    if [ "$?" -eq 0 ]; then
      # renew if possible
      TOKEN_RENEW=$(vault token-renew -format=json 2>/dev/null)
    else
      # authenticate
      approle_authenticate
    fi
  fi
fi
