#!/usr/bin/env bash
# shellcheck shell=bash
# Script for outputing values from the Vault KV
set -e
set -o pipefail
source /opt/hermes/bin/functions

if [ -e "$(which vault)" ]; then
  if [[ "$VAULT_ADDR" ]]; then
    get_vault_kv $1 $2
    echo -n $VAULT_KV
  else
    echo "MISSING VAULT_ADDR"
    exit 1
  fi
else
  echo "can not find vault"
  exit 1
fi
